library(mvtnorm) # to deal with multivariate normal distributions
library(car) # regression analysis
library(dplyr)
library( GGally)
library(maps)
library(leaflet) #to use the map
library(corrplot)

#Load data
itac = read.csv("ITACAs2s_2_flatfile/ITACAs2s_SA_2_0.csv", sep=";")
delta = itac[, 43:79]
dim(delta)
delta = na.omit(delta)
dim(delta)
colnames(delta) = c('t0_000','t0_010', 't0_025', 't0_040', 't0_050', 't0_070', 't0_100',
                    't0_150', 't0_200', 't0_250', 't0_300', 't0_350', 't0_400', 
                    't0_450', 't0_500','t0_600', 't0_700', 't0_750', 't0_800', 't0_900', 't1_000', 't1_200', 't1_400', 't1_600', 't1_800',
                    't2_000', 't2_500', 't3_000', 't3_500', 't4_000', 't4_500', 't5_000', 't6_000',
                    't7_000', 't8_000', 't9_000', 't10_000')

n = dim(delta)[1]
p = dim(delta)[2]
boxplot(delta, las = 2, col = 'gold') #detects depth to bedrock's outliers
boxplot(scale(x = delta, center = T, scale = F), las = 2, col = 'gold') #centering data (-mean to each column)
ds <- scale(delta)
pc.delta <- princomp(ds, scores = T) 
pc.delta
summary(pc.delta) #the first 5 components ok
#loadings
load.delta <- pc.delta$loadings
load.delta
#scores
scores.delta <- pc.delta$scores
#plot of original data
par(mfrow=c(2,1))
boxplot(ds, las = 2, col = 'gold', main = 'Original Variables')
boxplot(data.frame(scores.delta), las = 2, col = 'gold', main = 'Principal Components')

#Var
layout(matrix(c(2, 3, 1, 3), 2, byrow = TRUE))
barplot(pc.delta$sdev^2, las = 2, main = 'Principal Components', ylim = c(0, 26), ylab = 'Variances') 
abline(h = 1, col = 'blue')
barplot(apply(ds,2,var), las = 2, main = 'Original Variables', ylim = c(0, 4),
        ylab = 'Variances')
plot(cumsum(pc.delta$sdev^2) / sum(pc.delta$sde^2), type = 'b', axes = FALSE,
     xlab = 'Number of Components', ylab = 'Contribution to the Total Variance', ylim = c(0, 1))
box()
axis(2, at = 0:10/10, labels = 0:10/10)
axis(1, at = 1:ncol(ds), labels = 1:ncol(ds), las = 2)
abline(h = 0.95, col = 'red', lty = 2)



#plot of the first 4 PCA loadingsx
par(mar = c(1, 4, 0, 2), mfrow = c(4, 1))
for (i in 1:4) {
  barplot(load.delta[, i], ylim = c(-1, 1))
}
#plot only the most significant loadings
par(mar = c(1, 4, 0, 2), mfrow = c(4, 1))
for (i in 1:4) {
  barplot(ifelse(abs(load.delta[, i]) <0.15, 0, load.delta[, i]),
          ylim = c(-1, 1))
  abline(h = 0)
}
# Projection on the space generated by the first k principal components
par(mfrow = c(2, 5))
matplot(t(ds), type = 'l', main = 'Data', ylim = range(ds))
meanF <- colMeans(ds)
matplot(meanF, type = 'l', main = 'First 0 PCs', lwd = 2, ylim = range(ds))
projection <- matrix(meanF, dim(ds)[[1]], dim(ds)[[2]], byrow = T)
for (i in 1:8) {
  projection <- projection + scores.delta[, i] %*% t(load.delta[, i])
  matplot(t(projection), type = 'l', main = paste('First', i, 'PCs'), ylim = range(ds))
  matplot(meanF, type = 'l', lwd = 2, add = T)
} 

